import Navbar from "@/components/views/Navbar";
import "../../../globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const inter = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sanity Studio",
  description: "Generated by create next app",
};

export default function StudioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
